
namespace ProjectEuler.Problems
{
    internal class Problem002 : ProblemBase
    {
        private const int MAX_VALUE = 4000000;

        /// <summary>
        /// Even Fibonacci numbers
        /// 
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
        ///
        ///     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        ///
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// </summary>
        public Problem002() : base(2, "Even Fibonacci numbers") { }

        /// <inheritdoc />
        public override string Solve()
        {
            var first = 1;
            var second = 2;

            var sum = 0;
            while (second <= MAX_VALUE)
            {
                if (first % 2 == 0)
                    sum += first;
                if (second % 2 == 0)
                    sum += second;

                first = first + second;
                second = first + second;
            }

            return $"{sum}";
        }
    }
}